import rawReadings from './ja-readings.json'

// Generated by scripts/build-kanji-readings.mjs from KANJIDIC2: each value is
// "オン オン|くん.よみ くん" (on'yomi in katakana, kun'yomi in hiragana with
// "." marking where okurigana starts and "-" marking prefix/suffix use).
const table = rawReadings as Record<string, string>

export type KunReading = {
  /** The part the kanji itself covers (e.g. たか in たか.い). */
  stem: string
  /** Trailing kana written after the kanji (e.g. い). */
  okurigana: string
  /** Used as a prefix (なま-) or suffix (-び) rather than standalone. */
  affix: boolean
}

export type JaKanjiReadings = {
  on: string[]
  kun: KunReading[]
}

const cache = new Map<string, JaKanjiReadings | null>()

function parseKun(raw: string): KunReading {
  const affix = raw.startsWith('-') || raw.endsWith('-')
  const [stem, okurigana = ''] = raw.replace(/-/g, '').split('.')
  return { stem, okurigana, affix }
}

export function getJaReadings(char: string): JaKanjiReadings | null {
  if (cache.has(char)) return cache.get(char)!
  const entry = table[char]
  let result: JaKanjiReadings | null = null
  if (entry) {
    const [on, kun] = entry.split('|')
    // KANJIDIC lists the same word under several okurigana splits
    // (う.まれる / うま.れる) and as both a word and an affix (ゆ.き / -ゆ.き);
    // one entry per spelled-out reading is enough for a quick lookup.
    const seen = new Set<string>()
    const kunReadings: KunReading[] = []
    for (const reading of kun ? kun.split(' ').map(parseKun) : []) {
      const key = reading.stem + reading.okurigana
      if (seen.has(key)) continue
      seen.add(key)
      kunReadings.push(reading)
    }
    result = { on: on ? on.split(' ') : [], kun: kunReadings }
  }
  cache.set(char, result)
  return result
}

export function katakanaToHiragana(text: string): string {
  return text.replace(/[ァ-ヶ]/g, (ch) => String.fromCharCode(ch.charCodeAt(0) - 0x60))
}
